default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: sazanami_development

test:
  <<: *default
  database: sazanami_test

production:
  <<: *default
  database: sazanami_production
  username: sazanami
