default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.dig(:db, :host) || 'localhost' %>
  username: <%= Rails.application.credentials.dig(:db, :user) || ENV["DATABASE_USERNAME"] %>
  password: <%= Rails.application.credentials.dig(:db, :password) || ENV["DATABASE_PASSWORD"] %>
  port: <%= Rails.application.credentials.dig(:db, :port) || ENV["DATABASE_PORT"] %>

development:
  <<: *default
  database: sazanami_development

test:
  <<: *default
  database: sazanami_test

production:
  <<: *default
  database: sazanami_production
  username: sazanami
