inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - "tmp/*"
    - "db/schema.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 200

RSpec/ExampleLength:
  Max: 1000

RSpec/MultipleExpectations:
  Max: 20

RSpecRails/InferredSpecType:
  Exclude:
    - "spec/requests/**/*"
