services:
  db:
    image: postgres
    container_name: sazanami_db
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
